# = Service ===========================================================================================================
server:
  port: 8080

# = Eureka ===========================================================================================================
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

# = Spring ===========================================================================================================
spring:
  application:
    name: gateway