# = Service ===========================================================================================================
server:
  port: 8082
  
# = Eureka ===========================================================================================================
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

# = Spring ===========================================================================================================
spring:
  application:
    name: second-service